### PR TITLE
Volume control functionality added

### LINKED ISSUE #26: Add the volume control functionality to the frontend music player

### PR DESCRIPTION
**Pull request by shrishti-c**
Screenshot (132)

Issue #26

### CODE REVIEW

**Comment by Ayush-projects** [comment]
Looks nice, will merge it tomorrow after testing :)

**Comment by Ayush-projects** [comment]
Hey, there are some merge conflicts, can you resolve them and create another pull request? @shrishti-c

**Comment by Ayush-projects** [comment]
Hey, haven't you added the functionality of volume up or volume down? It's not working right now, there's just a seekbar for music control. If possible can you add a small sound logo in the end of the music control seek bar so that people can get to know that this is volume control functionality?

**Comment by shrishti-c** [comment]
Volume can be controlled by dragging the slider handle. If it's at top, volume will be highest and and vice versa. Yeah will add that logo.

**Comment by shrishti-c** [comment]
Seems you have already added that logo!!!

**Pull request merged**
